# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SampledSphere Frontend Deployment (QAS) CI

on:
  push:
    branches:
      - QA

jobs:
  build:
    environment: qas
    runs-on: ubuntu-latest
    env: # TODO: Fix linter issues and remove this env var (defaults to true)
      CI: false # Prevent build from being marked as failed due to linter warnings
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --legacy-peer-deps
    - run: npm run build-qas --if-present
    - run: npm run deploy-qas
    - run: npm run invalidate-cache-qas
